version: '3'

services:
  assetsecure:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assetsecure
    ports:
    - "8069:80"
    volumes:
    - ./storage/logs:/var/www/html/storage/logs
    depends_on:
    - mariadb
    - redis
    env_file:
    - .env.docker
    networks:
    - assetsecure-backend

  mariadb:
    image: mariadb:latest
    volumes:
    - db:/var/lib/mysql
    env_file:
    - .env.docker
    networks:
    - assetsecure-backend
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    networks:
    - assetsecure-backend

  mailhog:
    image: mailhog/mailhog:latest
    ports:
    # - 1025:1025
    - "8025:8025"
    networks:
    - assetsecure-backend


volumes:
  db: {}

networks:
  assetsecure-backend: {}
